source 'https://rubygems.org'

gem 'rake'
gem 'motion-cocoapods'
gem 'motion-settings-bundle', github: 'picapica/motion-settings-bundle'
gem 'motion-acknowledgements', github: 'picapica/motion-acknowledgements'

gem 'motion-kit'
gem 'motion-kit-events'
gem 'ProMotion'
gem 'ProMotion-menu'
gem 'sugarcube', :require => %w{sugarcube-color sugarcube-files sugarcube-foundation sugarcube-localized sugarcube-timer sugarcube-ui sugarcube-repl}
gem 'afmotion'
gem 'moticons'

gem 'motion-html'
gem 'motion-blitz'
gem 'rm-digest'
