#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."

APP="${1:-TestApp}"
rm -rf "vendor/gems"

[ -z "$DEBUG" ] || set -x

RACK_ROOT="$(cd "$(dirname "$0")"/.. && pwd)"
export RACK_ROOT

if [ "$CI" = "true" ] || [ "$RAILS_ENV" = "test" ] || [ "$RACK_ENV" = "test" ]; then
  # if executed and the environment is already set to `test`, then we want a
  # clean from scratch application. This almost always means a ci environment,
  # since we set the environment to `test` directly in `script/cibuild`.
  script/setup "$APP"
else
  # if the environment isn't set to `test`, set it to `test` and update the
  # application to ensure all dependencies are met as well as any other things
  # that need to be up to date, like db migrations. The environment not having
  # already been set to `test` almost always means this is being called on it's
  # own from a `development` environment.
  export CI=true RAILS_ENV="test" RACK_ENV="test"

  script/update "$APP"
fi

echo "==> Running tests…"

rm -rf "./$APP"
bundle exec motion create --template=circle "$APP" && \
  cd "$APP" && export BUNDLE_GEMFILE=$(pwd)/Gemfile

if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  script/test "$1"
else
  script/test
fi
