source 'https://rubygems.org'

gem 'rake'
gem 'motion-cocoapods'
gem 'motion-settings-bundle', github: 'picapica/motion-settings-bundle'
gem 'motion-acknowledgements', github: 'picapica/motion-acknowledgements'
